#!/usr/bin/env python3

import rospy
from std_msgs.msg import String
from mech_buggy2 import MechBuggy2

# Make sure wires are right way around
# Fr left  Fr right
# Bk left  Bk right
wires = ((12,6), (13,5), \
		 (0,1), (7,8))
buggy = MechBuggy2(wires)
duty = 0.5

def callback(msg):
	rospy.loginfo("%r I heard: %s", rospy.get_caller_id(), msg.data)
	buggy.cmd_handler(msg.data, duty)


def main():

	rospy.init_node("sub")
	rospy.Subscriber('cmd', String, callback)
	rospy.spin()


if __name__ == "__main__":
	try:
		main()
	except KeyboardInterrupt:
		pass
